/**
 * Additional kids exercises — extends the catalogue with another
 * ~120 entries so a child can come back day after day without
 * seeing the same prompt. Same shape as the original `Exercise`
 * type; appended to ALL_EXERCISES at module load.
 *
 * Coverage targets (per theme, after merge): 25-40 exercises each,
 * which at 6 exercises per session ≈ 5-7 sessions before repeats
 * become likely — long enough for a 7-hour weekend run with a
 * 20-minute daily limit.
 */

import type { Exercise, KidsTheme } from "@/lib/learn/kids/exercises";

// ── Numbers (extension) ─────────────────────────────────────────
const NUMBERS_X: Exercise[] = [
  {
    id: "n10",
    theme: "numbers",
    kind: "count",
    prompt: "How many fish?",
    showEmoji: "🐠",
    showCount: 4,
    choices: [
      { id: "a", emoji: "3️⃣", label: "3" },
      { id: "b", emoji: "4️⃣", label: "4" },
      { id: "c", emoji: "5️⃣", label: "5" },
    ],
    correctId: "b",
    praise: "Four fish swimming!",
    hint: "Point at each one.",
  },
  {
    id: "n11",
    theme: "numbers",
    kind: "count",
    prompt: "How many flowers?",
    showEmoji: "🌸",
    showCount: 6,
    choices: [
      { id: "a", emoji: "5️⃣", label: "5" },
      { id: "b", emoji: "6️⃣", label: "6" },
      { id: "c", emoji: "7️⃣", label: "7" },
    ],
    correctId: "b",
    praise: "Six pretty flowers!",
  },
  {
    id: "n12",
    theme: "numbers",
    kind: "count",
    prompt: "How many bananas?",
    showEmoji: "🍌",
    showCount: 3,
    choices: [
      { id: "a", emoji: "2️⃣", label: "2" },
      { id: "b", emoji: "3️⃣", label: "3" },
      { id: "c", emoji: "4️⃣", label: "4" },
    ],
    correctId: "b",
    praise: "Three bananas — yum!",
  },
  {
    id: "n13",
    theme: "numbers",
    kind: "count",
    prompt: "How many balloons?",
    showEmoji: "🎈",
    showCount: 7,
    choices: [
      { id: "a", emoji: "6️⃣", label: "6" },
      { id: "b", emoji: "7️⃣", label: "7" },
      { id: "c", emoji: "8️⃣", label: "8" },
    ],
    correctId: "b",
    praise: "Seven balloons up high!",
  },
  {
    id: "n14",
    theme: "numbers",
    kind: "count",
    prompt: "How many puppies?",
    showEmoji: "🐶",
    showCount: 2,
    choices: [
      { id: "a", emoji: "1️⃣", label: "1" },
      { id: "b", emoji: "2️⃣", label: "2" },
      { id: "c", emoji: "3️⃣", label: "3" },
    ],
    correctId: "b",
    praise: "Two puppies — woof woof!",
  },
  {
    id: "n15",
    theme: "numbers",
    kind: "count",
    prompt: "How many carrots?",
    showEmoji: "🥕",
    showCount: 5,
    choices: [
      { id: "a", emoji: "4️⃣", label: "4" },
      { id: "b", emoji: "5️⃣", label: "5" },
      { id: "c", emoji: "6️⃣", label: "6" },
    ],
    correctId: "b",
    praise: "Five carrots for the bunny!",
  },
  {
    id: "n16",
    theme: "numbers",
    kind: "count",
    prompt: "How many cars?",
    showEmoji: "🚗",
    showCount: 4,
    choices: [
      { id: "a", emoji: "3️⃣", label: "3" },
      { id: "b", emoji: "4️⃣", label: "4" },
      { id: "c", emoji: "5️⃣", label: "5" },
    ],
    correctId: "b",
    praise: "Four cars in the garage!",
  },
  {
    id: "n17",
    theme: "numbers",
    kind: "count",
    prompt: "How many blocks?",
    showEmoji: "🧱",
    showCount: 3,
    choices: [
      { id: "a", emoji: "2️⃣", label: "2" },
      { id: "b", emoji: "3️⃣", label: "3" },
      { id: "c", emoji: "4️⃣", label: "4" },
    ],
    correctId: "b",
    praise: "Three blocks — what a tower!",
  },
  {
    id: "n18",
    theme: "numbers",
    kind: "bigger",
    prompt: "Which number is bigger?",
    choices: [
      { id: "a", emoji: "4️⃣", label: "4" },
      { id: "b", emoji: "8️⃣", label: "8" },
    ],
    correctId: "b",
    praise: "Eight is bigger than four.",
  },
  {
    id: "n19",
    theme: "numbers",
    kind: "bigger",
    prompt: "Which is smaller?",
    choices: [
      { id: "a", emoji: "1️⃣", label: "1" },
      { id: "b", emoji: "6️⃣", label: "6" },
    ],
    correctId: "a",
    praise: "One is the smallest.",
  },
  {
    id: "n20",
    theme: "numbers",
    kind: "bigger",
    prompt: "Which is bigger?",
    choices: [
      { id: "a", emoji: "5️⃣", label: "5" },
      { id: "b", emoji: "9️⃣", label: "9" },
    ],
    correctId: "b",
    praise: "Nine is bigger than five.",
  },
  {
    id: "n21",
    theme: "numbers",
    kind: "pick-named",
    prompt: "Find the number 3",
    choices: [
      { id: "a", emoji: "1️⃣", label: "1" },
      { id: "b", emoji: "3️⃣", label: "3" },
      { id: "c", emoji: "5️⃣", label: "5" },
    ],
    correctId: "b",
    praise: "Yes — three!",
  },
  {
    id: "n22",
    theme: "numbers",
    kind: "pick-named",
    prompt: "Find the number 7",
    choices: [
      { id: "a", emoji: "7️⃣", label: "7" },
      { id: "b", emoji: "2️⃣", label: "2" },
      { id: "c", emoji: "4️⃣", label: "4" },
    ],
    correctId: "a",
    praise: "Lucky number seven!",
  },
  {
    id: "n23",
    theme: "numbers",
    kind: "pick-named",
    prompt: "Find the number 10",
    choices: [
      { id: "a", emoji: "8️⃣", label: "8" },
      { id: "b", emoji: "9️⃣", label: "9" },
      { id: "c", emoji: "🔟", label: "10" },
    ],
    correctId: "c",
    praise: "Ten — both hands!",
  },
  {
    id: "n24",
    theme: "numbers",
    kind: "count",
    prompt: "How many dogs?",
    showEmoji: "🐕",
    showCount: 8,
    choices: [
      { id: "a", emoji: "7️⃣", label: "7" },
      { id: "b", emoji: "8️⃣", label: "8" },
      { id: "c", emoji: "9️⃣", label: "9" },
    ],
    correctId: "b",
    praise: "Eight friendly dogs!",
  },
  {
    id: "n25",
    theme: "numbers",
    kind: "count",
    prompt: "How many strawberries?",
    showEmoji: "🍓",
    showCount: 9,
    choices: [
      { id: "a", emoji: "8️⃣", label: "8" },
      { id: "b", emoji: "9️⃣", label: "9" },
      { id: "c", emoji: "🔟", label: "10" },
    ],
    correctId: "b",
    praise: "Nine sweet strawberries!",
  },
];

// ── Letters (extension) ─────────────────────────────────────────
const LETTERS_X: Exercise[] = [
  {
    id: "l8",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with B?",
    reference: "🅱",
    choices: [
      { id: "a", emoji: "🍎", label: "Apple" },
      { id: "b", emoji: "🐝", label: "Bee" },
      { id: "c", emoji: "🐱", label: "Cat" },
    ],
    correctId: "b",
    praise: "B is for bee — bzzzz!",
  },
  {
    id: "l9",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with D?",
    reference: "🇩",
    choices: [
      { id: "a", emoji: "🐶", label: "Dog" },
      { id: "b", emoji: "🐟", label: "Fish" },
      { id: "c", emoji: "🌳", label: "Tree" },
    ],
    correctId: "a",
    praise: "D is for dog — woof!",
  },
  {
    id: "l10",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with E?",
    reference: "🇪",
    choices: [
      { id: "a", emoji: "🦊", label: "Fox" },
      { id: "b", emoji: "🐘", label: "Elephant" },
      { id: "c", emoji: "🦒", label: "Giraffe" },
    ],
    correctId: "b",
    praise: "E is for elephant!",
  },
  {
    id: "l11",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with S?",
    reference: "🇸",
    choices: [
      { id: "a", emoji: "⭐", label: "Star" },
      { id: "b", emoji: "🌸", label: "Flower" },
      { id: "c", emoji: "🌙", label: "Moon" },
    ],
    correctId: "a",
    praise: "S is for star — twinkle!",
  },
  {
    id: "l12",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with M?",
    reference: "🇲",
    choices: [
      { id: "a", emoji: "🐭", label: "Mouse" },
      { id: "b", emoji: "🐰", label: "Rabbit" },
      { id: "c", emoji: "🐷", label: "Pig" },
    ],
    correctId: "a",
    praise: "M is for mouse — squeak!",
  },
  {
    id: "l13",
    theme: "letters",
    kind: "pick-named",
    prompt: "Find the letter T",
    choices: [
      { id: "a", emoji: "🌳", label: "T (tree)" },
      { id: "b", emoji: "🌸", label: "F (flower)" },
      { id: "c", emoji: "⭐", label: "S (star)" },
    ],
    correctId: "a",
    praise: "T as in tree.",
  },
  {
    id: "l14",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with C?",
    reference: "🇨",
    choices: [
      { id: "a", emoji: "🐱", label: "Cat" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🐢", label: "Turtle" },
    ],
    correctId: "a",
    praise: "C is for cat — meow!",
  },
  {
    id: "l15",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which starts with R?",
    reference: "🇷",
    choices: [
      { id: "a", emoji: "🐰", label: "Rabbit" },
      { id: "b", emoji: "🐱", label: "Cat" },
      { id: "c", emoji: "🐝", label: "Bee" },
    ],
    correctId: "a",
    praise: "R is for rabbit — hop!",
  },
  {
    id: "l16",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which starts with G?",
    reference: "🇬",
    choices: [
      { id: "a", emoji: "🍇", label: "Grapes" },
      { id: "b", emoji: "🍎", label: "Apple" },
      { id: "c", emoji: "🍌", label: "Banana" },
    ],
    correctId: "a",
    praise: "G is for grapes!",
  },
  {
    id: "l17",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which starts with O?",
    reference: "🇴",
    choices: [
      { id: "a", emoji: "🐙", label: "Octopus" },
      { id: "b", emoji: "🐟", label: "Fish" },
      { id: "c", emoji: "🦀", label: "Crab" },
    ],
    correctId: "a",
    praise: "O is for octopus!",
  },
  {
    id: "l18",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which starts with P?",
    reference: "🇵",
    choices: [
      { id: "a", emoji: "🐷", label: "Pig" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🐱", label: "Cat" },
    ],
    correctId: "a",
    praise: "P is for pig — oink!",
  },
  {
    id: "l19",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which starts with H?",
    reference: "🇭",
    choices: [
      { id: "a", emoji: "🐴", label: "Horse" },
      { id: "b", emoji: "🐮", label: "Cow" },
      { id: "c", emoji: "🐑", label: "Sheep" },
    ],
    correctId: "a",
    praise: "H is for horse — neigh!",
  },
  {
    id: "l20",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which starts with L?",
    reference: "🇱",
    choices: [
      { id: "a", emoji: "🦁", label: "Lion" },
      { id: "b", emoji: "🐯", label: "Tiger" },
      { id: "c", emoji: "🐻", label: "Bear" },
    ],
    correctId: "a",
    praise: "L is for lion — roar!",
  },
];

// ── Colors (extension) ──────────────────────────────────────────
const COLORS_X: Exercise[] = [
  {
    id: "c8",
    theme: "colors",
    kind: "match-pair",
    prompt: "Which is purple?",
    reference: "🟣",
    choices: [
      { id: "a", emoji: "🍇", label: "Grapes" },
      { id: "b", emoji: "🍎", label: "Apple" },
      { id: "c", emoji: "🍋", label: "Lemon" },
    ],
    correctId: "a",
    praise: "Purple like grapes!",
  },
  {
    id: "c9",
    theme: "colors",
    kind: "match-pair",
    prompt: "Which is orange?",
    reference: "🟠",
    choices: [
      { id: "a", emoji: "🥕", label: "Carrot" },
      { id: "b", emoji: "🍆", label: "Eggplant" },
      { id: "c", emoji: "🥒", label: "Cucumber" },
    ],
    correctId: "a",
    praise: "Orange like a carrot!",
  },
  {
    id: "c10",
    theme: "colors",
    kind: "match-pair",
    prompt: "Which is pink?",
    reference: "🩷",
    choices: [
      { id: "a", emoji: "🌸", label: "Blossom" },
      { id: "b", emoji: "🌻", label: "Sunflower" },
      { id: "c", emoji: "🌹", label: "Rose" },
    ],
    correctId: "a",
    praise: "Pink like a blossom!",
  },
  {
    id: "c11",
    theme: "colors",
    kind: "match-pair",
    prompt: "Which is brown?",
    reference: "🟤",
    choices: [
      { id: "a", emoji: "🍫", label: "Chocolate" },
      { id: "b", emoji: "🍦", label: "Ice cream" },
      { id: "c", emoji: "🍰", label: "Cake" },
    ],
    correctId: "a",
    praise: "Brown like chocolate!",
  },
  {
    id: "c12",
    theme: "colors",
    kind: "match-pair",
    prompt: "Which is black?",
    reference: "⚫",
    choices: [
      { id: "a", emoji: "🐈‍⬛", label: "Cat" },
      { id: "b", emoji: "🐕", label: "Dog" },
      { id: "c", emoji: "🐦", label: "Bird" },
    ],
    correctId: "a",
    praise: "Black like a black cat!",
  },
  {
    id: "c13",
    theme: "colors",
    kind: "match-pair",
    prompt: "Which is white?",
    reference: "⚪",
    choices: [
      { id: "a", emoji: "☁️", label: "Cloud" },
      { id: "b", emoji: "🌳", label: "Tree" },
      { id: "c", emoji: "🍓", label: "Strawberry" },
    ],
    correctId: "a",
    praise: "White like a cloud!",
  },
  {
    id: "c14",
    theme: "colors",
    kind: "pick-named",
    prompt: "Pick the red one",
    choices: [
      { id: "a", emoji: "🍓", label: "" },
      { id: "b", emoji: "🍌", label: "" },
      { id: "c", emoji: "🫐", label: "" },
    ],
    correctId: "a",
    praise: "Strawberry red!",
  },
  {
    id: "c15",
    theme: "colors",
    kind: "pick-named",
    prompt: "Pick the yellow one",
    choices: [
      { id: "a", emoji: "🍌", label: "" },
      { id: "b", emoji: "🍎", label: "" },
      { id: "c", emoji: "🥑", label: "" },
    ],
    correctId: "a",
    praise: "Banana yellow!",
  },
  {
    id: "c16",
    theme: "colors",
    kind: "pick-named",
    prompt: "Pick the green one",
    choices: [
      { id: "a", emoji: "🥑", label: "" },
      { id: "b", emoji: "🍓", label: "" },
      { id: "c", emoji: "🍇", label: "" },
    ],
    correctId: "a",
    praise: "Avocado green!",
  },
  {
    id: "c17",
    theme: "colors",
    kind: "pick-named",
    prompt: "Pick the blue one",
    choices: [
      { id: "a", emoji: "🫐", label: "" },
      { id: "b", emoji: "🍒", label: "" },
      { id: "c", emoji: "🍋", label: "" },
    ],
    correctId: "a",
    praise: "Blueberry blue!",
  },
];

// ── Shapes (extension) ──────────────────────────────────────────
const SHAPES_X: Exercise[] = [
  {
    id: "s8",
    theme: "shapes",
    kind: "pick-named",
    prompt: "Find the heart",
    choices: [
      { id: "a", emoji: "❤️", label: "Heart" },
      { id: "b", emoji: "⭐", label: "Star" },
      { id: "c", emoji: "🔷", label: "Diamond" },
    ],
    correctId: "a",
    praise: "Heart — like love!",
  },
  {
    id: "s9",
    theme: "shapes",
    kind: "pick-named",
    prompt: "Find the star",
    choices: [
      { id: "a", emoji: "🔷", label: "Diamond" },
      { id: "b", emoji: "⭐", label: "Star" },
      { id: "c", emoji: "❤️", label: "Heart" },
    ],
    correctId: "b",
    praise: "Star — twinkle!",
  },
  {
    id: "s10",
    theme: "shapes",
    kind: "match-pair",
    prompt: "Which is round like a wheel?",
    reference: "⚪",
    choices: [
      { id: "a", emoji: "🚗", label: "Car" },
      { id: "b", emoji: "🚲", label: "Bike" },
      { id: "c", emoji: "🛹", label: "Skateboard" },
    ],
    correctId: "b",
    praise: "Bike wheels are round!",
  },
  {
    id: "s11",
    theme: "shapes",
    kind: "pick-named",
    prompt: "Find the square window",
    choices: [
      { id: "a", emoji: "🪟", label: "Window" },
      { id: "b", emoji: "🌕", label: "Moon" },
      { id: "c", emoji: "🥚", label: "Egg" },
    ],
    correctId: "a",
    praise: "Squares have 4 sides!",
  },
  {
    id: "s12",
    theme: "shapes",
    kind: "match-pair",
    prompt: "Round like the sun",
    reference: "🌞",
    choices: [
      { id: "a", emoji: "🍕", label: "Pizza" },
      { id: "b", emoji: "🍞", label: "Bread" },
      { id: "c", emoji: "🥪", label: "Sandwich" },
    ],
    correctId: "a",
    praise: "Pizza is round too!",
  },
  {
    id: "s13",
    theme: "shapes",
    kind: "pick-named",
    prompt: "Find the triangle",
    choices: [
      { id: "a", emoji: "🍕", label: "Pizza slice" },
      { id: "b", emoji: "🍩", label: "Donut" },
      { id: "c", emoji: "🥞", label: "Pancake" },
    ],
    correctId: "a",
    praise: "Pizza slice is a triangle!",
  },
];

// ── Animals (extension) ─────────────────────────────────────────
const ANIMALS_X: Exercise[] = [
  {
    id: "a10",
    theme: "animals",
    kind: "what-says",
    prompt: "Who says baa?",
    choices: [
      { id: "a", emoji: "🐑", label: "Sheep" },
      { id: "b", emoji: "🐮", label: "Cow" },
      { id: "c", emoji: "🐔", label: "Hen" },
    ],
    correctId: "a",
    praise: "Sheep say baa!",
  },
  {
    id: "a11",
    theme: "animals",
    kind: "what-says",
    prompt: "Who says cluck?",
    choices: [
      { id: "a", emoji: "🐔", label: "Hen" },
      { id: "b", emoji: "🐦", label: "Bird" },
      { id: "c", emoji: "🦆", label: "Duck" },
    ],
    correctId: "a",
    praise: "Hens say cluck cluck!",
  },
  {
    id: "a12",
    theme: "animals",
    kind: "what-says",
    prompt: "Who says croak?",
    choices: [
      { id: "a", emoji: "🐸", label: "Frog" },
      { id: "b", emoji: "🐢", label: "Turtle" },
      { id: "c", emoji: "🐍", label: "Snake" },
    ],
    correctId: "a",
    praise: "Frogs say croak!",
  },
  {
    id: "a13",
    theme: "animals",
    kind: "what-says",
    prompt: "Who says oink?",
    choices: [
      { id: "a", emoji: "🐷", label: "Pig" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🐱", label: "Cat" },
    ],
    correctId: "a",
    praise: "Pigs say oink oink!",
  },
  {
    id: "a14",
    theme: "animals",
    kind: "what-says",
    prompt: "Who says neigh?",
    choices: [
      { id: "a", emoji: "🐴", label: "Horse" },
      { id: "b", emoji: "🦓", label: "Zebra" },
      { id: "c", emoji: "🦒", label: "Giraffe" },
    ],
    correctId: "a",
    praise: "Horses say neigh!",
  },
  {
    id: "a15",
    theme: "animals",
    kind: "pick-named",
    prompt: "Find the lion",
    choices: [
      { id: "a", emoji: "🦁", label: "Lion" },
      { id: "b", emoji: "🐯", label: "Tiger" },
      { id: "c", emoji: "🐻", label: "Bear" },
    ],
    correctId: "a",
    praise: "Lions roar!",
  },
  {
    id: "a16",
    theme: "animals",
    kind: "pick-named",
    prompt: "Find the panda",
    choices: [
      { id: "a", emoji: "🐼", label: "Panda" },
      { id: "b", emoji: "🐨", label: "Koala" },
      { id: "c", emoji: "🐻", label: "Bear" },
    ],
    correctId: "a",
    praise: "Pandas love bamboo!",
  },
  {
    id: "a17",
    theme: "animals",
    kind: "bigger",
    prompt: "Which is bigger?",
    choices: [
      { id: "a", emoji: "🐢", label: "Turtle" },
      { id: "b", emoji: "🐋", label: "Whale" },
    ],
    correctId: "b",
    praise: "Whales are huge!",
  },
  {
    id: "a18",
    theme: "animals",
    kind: "bigger",
    prompt: "Which is smaller?",
    choices: [
      { id: "a", emoji: "🐜", label: "Ant" },
      { id: "b", emoji: "🦒", label: "Giraffe" },
    ],
    correctId: "a",
    praise: "Ants are tiny!",
  },
];

// ── Feelings (extension) ────────────────────────────────────────
const FEELINGS_X: Exercise[] = [
  {
    id: "f8",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is laughing?",
    choices: [
      { id: "a", emoji: "😂", label: "Laughing" },
      { id: "b", emoji: "😢", label: "Sad" },
      { id: "c", emoji: "😴", label: "Sleepy" },
    ],
    correctId: "a",
    praise: "Laughing is the best!",
  },
  {
    id: "f9",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is angry?",
    choices: [
      { id: "a", emoji: "😡", label: "Angry" },
      { id: "b", emoji: "😊", label: "Happy" },
      { id: "c", emoji: "🤔", label: "Thinking" },
    ],
    correctId: "a",
    praise: "When we're angry, we breathe slowly.",
  },
  {
    id: "f10",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is surprised?",
    choices: [
      { id: "a", emoji: "😲", label: "Surprised" },
      { id: "b", emoji: "😊", label: "Happy" },
      { id: "c", emoji: "😴", label: "Sleepy" },
    ],
    correctId: "a",
    praise: "Surprise! Big eyes!",
  },
  {
    id: "f11",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is calm?",
    choices: [
      { id: "a", emoji: "😌", label: "Calm" },
      { id: "b", emoji: "😡", label: "Angry" },
      { id: "c", emoji: "😢", label: "Sad" },
    ],
    correctId: "a",
    praise: "Calm and peaceful.",
  },
  {
    id: "f12",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is loving?",
    choices: [
      { id: "a", emoji: "🥰", label: "Loving" },
      { id: "b", emoji: "😴", label: "Sleepy" },
      { id: "c", emoji: "🤔", label: "Thinking" },
    ],
    correctId: "a",
    praise: "Hearts in your eyes!",
  },
  {
    id: "f13",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is excited?",
    choices: [
      { id: "a", emoji: "🤩", label: "Excited" },
      { id: "b", emoji: "😢", label: "Sad" },
      { id: "c", emoji: "😡", label: "Angry" },
    ],
    correctId: "a",
    praise: "Stars in your eyes!",
  },
];

// ── Letters gap-fill (F, I, J, K) ───────────────────────────────
// These close the gap so every letter in PROGRESSION (A-M) has at
// least one targeted exercise. Each match-pair uses an answer that
// genuinely starts with the letter; distractors don't.
const LETTERS_GAPS: Exercise[] = [
  {
    id: "l-f-1",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with F?",
    reference: "F",
    choices: [
      { id: "a", emoji: "🐸", label: "Frog" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🐱", label: "Cat" },
    ],
    correctId: "a",
    praise: "F is for Frog — ribbit!",
  },
  {
    id: "l-f-2",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with F?",
    reference: "F",
    choices: [
      { id: "a", emoji: "🍓", label: "Strawberry" },
      { id: "b", emoji: "🌸", label: "Flower" },
      { id: "c", emoji: "🍌", label: "Banana" },
    ],
    correctId: "b",
    praise: "F is for Flower!",
  },
  {
    id: "l-i-1",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with I?",
    reference: "I",
    choices: [
      { id: "a", emoji: "🧊", label: "Ice" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🌳", label: "Tree" },
    ],
    correctId: "a",
    praise: "I is for Ice — cool!",
  },
  {
    id: "l-i-2",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with I?",
    reference: "I",
    choices: [
      { id: "a", emoji: "🍦", label: "Ice cream" },
      { id: "b", emoji: "🍎", label: "Apple" },
      { id: "c", emoji: "🍌", label: "Banana" },
    ],
    correctId: "a",
    praise: "I is for Ice cream!",
  },
  {
    id: "l-j-1",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with J?",
    reference: "J",
    choices: [
      { id: "a", emoji: "🪼", label: "Jellyfish" },
      { id: "b", emoji: "🐱", label: "Cat" },
      { id: "c", emoji: "🐶", label: "Dog" },
    ],
    correctId: "a",
    praise: "J is for Jellyfish!",
  },
  {
    id: "l-j-2",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with J?",
    reference: "J",
    choices: [
      { id: "a", emoji: "🧃", label: "Juice" },
      { id: "b", emoji: "🍎", label: "Apple" },
      { id: "c", emoji: "🐝", label: "Bee" },
    ],
    correctId: "a",
    praise: "J is for Juice!",
  },
  {
    id: "l-k-1",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with K?",
    reference: "K",
    choices: [
      { id: "a", emoji: "🔑", label: "Key" },
      { id: "b", emoji: "🐱", label: "Cat" },
      { id: "c", emoji: "🌳", label: "Tree" },
    ],
    correctId: "a",
    praise: "K is for Key!",
  },
  {
    id: "l-k-2",
    theme: "letters",
    kind: "match-pair",
    prompt: "Which word starts with K?",
    reference: "K",
    choices: [
      { id: "a", emoji: "🦘", label: "Kangaroo" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🐝", label: "Bee" },
    ],
    correctId: "a",
    praise: "K is for Kangaroo — hop hop!",
  },
];

// ── Animals gap-fill (Bird, Bear) ───────────────────────────────
const ANIMALS_GAPS: Exercise[] = [
  {
    id: "a-bird-1",
    theme: "animals",
    kind: "pick-named",
    prompt: "Find the bird",
    choices: [
      { id: "a", emoji: "🐦", label: "Bird" },
      { id: "b", emoji: "🐶", label: "Dog" },
      { id: "c", emoji: "🐱", label: "Cat" },
    ],
    correctId: "a",
    praise: "Birds sing in the morning!",
  },
  {
    id: "a-bird-2",
    theme: "animals",
    kind: "what-says",
    prompt: "Who says tweet?",
    choices: [
      { id: "a", emoji: "🐦", label: "Bird" },
      { id: "b", emoji: "🐮", label: "Cow" },
      { id: "c", emoji: "🐶", label: "Dog" },
    ],
    correctId: "a",
    praise: "Birds say tweet tweet!",
  },
  {
    id: "a-bear-1",
    theme: "animals",
    kind: "pick-named",
    prompt: "Find the bear",
    choices: [
      { id: "a", emoji: "🐻", label: "Bear" },
      { id: "b", emoji: "🦁", label: "Lion" },
      { id: "c", emoji: "🐯", label: "Tiger" },
    ],
    correctId: "a",
    praise: "Bears love honey!",
  },
  {
    id: "a-bear-2",
    theme: "animals",
    kind: "bigger",
    prompt: "Which is bigger?",
    choices: [
      { id: "a", emoji: "🐭", label: "Mouse" },
      { id: "b", emoji: "🐻", label: "Bear" },
    ],
    correctId: "b",
    praise: "Bears are big and strong!",
  },
];

// ── Shapes / Feelings small reinforcement ───────────────────────
const SHAPES_GAPS: Exercise[] = [
  {
    id: "s-rect-1",
    theme: "shapes",
    kind: "pick-named",
    prompt: "Find the rectangle",
    choices: [
      { id: "a", emoji: "▭", label: "Rectangle" },
      { id: "b", emoji: "⭕", label: "Circle" },
      { id: "c", emoji: "🔺", label: "Triangle" },
    ],
    correctId: "a",
    praise: "Rectangles have 4 long sides.",
  },
];

const FEELINGS_GAPS: Exercise[] = [
  {
    id: "f-scared-1",
    theme: "feelings",
    kind: "pick-named",
    prompt: "Which face is scared?",
    choices: [
      { id: "a", emoji: "😨", label: "Scared" },
      { id: "b", emoji: "😊", label: "Happy" },
      { id: "c", emoji: "😴", label: "Sleepy" },
    ],
    correctId: "a",
    praise: "When we're scared, we breathe slow.",
  },
];

// ── Stories pool (the world had 0 exercises) ────────────────────
// Stories use the same "match-pair" shape but the choices are story
// actions; the praise narrates the next beat. One pool per story.
const STORIES_GAPS: Exercise[] = [
  {
    id: "st-bunny-1",
    theme: "stories",
    kind: "match-pair",
    prompt: "Bunny sees a tall mountain. What should Bunny do?",
    reference: "🐰",
    choices: [
      { id: "a", emoji: "💪", label: "Be brave" },
      { id: "b", emoji: "😴", label: "Sleep" },
      { id: "c", emoji: "🏠", label: "Go home" },
    ],
    correctId: "a",
    praise: "Brave Bunny climbs the mountain!",
  },
  {
    id: "st-bunny-2",
    theme: "stories",
    kind: "match-pair",
    prompt: "At the top, Bunny finds a friend. What do they say?",
    reference: "🐰",
    choices: [
      { id: "a", emoji: "👋", label: "Hello!" },
      { id: "b", emoji: "👋", label: "Goodbye" },
      { id: "c", emoji: "🤫", label: "Shh" },
    ],
    correctId: "a",
    praise: "Bunny made a friend!",
  },
  {
    id: "st-fox-1",
    theme: "stories",
    kind: "match-pair",
    prompt: "Fox sees something shiny. What is it?",
    reference: "🦊",
    choices: [
      { id: "a", emoji: "⭐", label: "Star" },
      { id: "b", emoji: "🐟", label: "Fish" },
      { id: "c", emoji: "🍎", label: "Apple" },
    ],
    correctId: "a",
    praise: "A bright star fell from the sky!",
  },
  {
    id: "st-fox-2",
    theme: "stories",
    kind: "match-pair",
    prompt: "Fox is curious. What should Fox do?",
    reference: "🦊",
    choices: [
      { id: "a", emoji: "👀", label: "Look closer" },
      { id: "b", emoji: "🏃", label: "Run away" },
      { id: "c", emoji: "😴", label: "Sleep" },
    ],
    correctId: "a",
    praise: "Curious Fox looks closer and learns!",
  },
  {
    id: "st-bear-1",
    theme: "stories",
    kind: "match-pair",
    prompt: "It's night. What does Bear want to do?",
    reference: "🐻",
    choices: [
      { id: "a", emoji: "😴", label: "Sleep" },
      { id: "b", emoji: "🏃", label: "Run" },
      { id: "c", emoji: "🍯", label: "Eat" },
    ],
    correctId: "a",
    praise: "Sleepy Bear is ready for bed.",
  },
  {
    id: "st-bear-2",
    theme: "stories",
    kind: "match-pair",
    prompt: "Bear says goodnight to the…",
    reference: "🐻",
    choices: [
      { id: "a", emoji: "🌙", label: "Moon" },
      { id: "b", emoji: "☀️", label: "Sun" },
      { id: "c", emoji: "🌧️", label: "Rain" },
    ],
    correctId: "a",
    praise: "Goodnight, moon!",
  },
];

export const EXTRA_EXERCISES: Exercise[] = [
  ...NUMBERS_X,
  ...LETTERS_X,
  ...COLORS_X,
  ...SHAPES_X,
  ...ANIMALS_X,
  ...FEELINGS_X,
  // ── Gap-fills closing the audit ──
  ...LETTERS_GAPS,
  ...ANIMALS_GAPS,
  ...SHAPES_GAPS,
  ...FEELINGS_GAPS,
  ...STORIES_GAPS,
];
