import type { LearnerStage } from "./stages";
import { type LearningMethodId, type LoopStepId, planForStage } from "./methods";
import { type Exercise, generateForMethod } from "./quizzes";

export type LessonTask = {
  prompt: string;
  hint?: string;
  expected?: string;
  choices?: string[];
};

export type Lesson = {
  stage: LearnerStage;
  goal: string;
  language: string;
  attentionMinutes: number;
  teacherName: string;
  hook: string;
  explain: string;
  tasks: LessonTask[];
  reward: string;
  /** Which historical method drives each Loop step. */
  methodPlan: Record<LoopStepId, LearningMethodId>;
  /** Typed exercises generated by those methods, in Loop order. */
  exercises: Exercise[];
};

const STAGE_DEFAULTS: Record<
  LearnerStage,
  { attentionMinutes: number; tasks: number; reward: string }
> = {
  GRADE_6: { attentionMinutes: 5, tasks: 1, reward: "⭐ Great job!" },
  GRADE_7: { attentionMinutes: 10, tasks: 3, reward: "🏅 Quest badge earned" },
  GRADE_8: { attentionMinutes: 20, tasks: 4, reward: "🛠️ Mission step complete" },
  GRADE_9: { attentionMinutes: 25, tasks: 5, reward: "📈 Mastery +1" },
  UNIVERSITY: { attentionMinutes: 30, tasks: 6, reward: "✅ Module checkpoint" },
  PROFESSIONAL: { attentionMinutes: 30, tasks: 6, reward: "✅ Module checkpoint" },
  SENIOR: { attentionMinutes: 15, tasks: 2, reward: "👏 Well done — take your time" },
};

function hookFor(stage: LearnerStage, goal: string, teacherName: string): string {
  switch (stage) {
    case "GRADE_6":
      return `${teacherName} says: let's play with ${goal.toLowerCase()}!`;
    case "GRADE_7":
      return `Today's quest: discover ${goal.toLowerCase()}.`;
    case "GRADE_8":
      return `Mission: build something with ${goal.toLowerCase()}.`;
    case "GRADE_9":
      return `Focused session: ${goal}. We'll target your weak spots.`;
    case "UNIVERSITY":
    case "PROFESSIONAL":
      return `Deep dive: ${goal}. Learn → practice → review.`;
    case "SENIOR":
      return `Practical lesson: ${goal}. We will go slowly and repeat as needed.`;
  }
}

function explainFor(stage: LearnerStage, goal: string): string {
  switch (stage) {
    case "GRADE_6":
      return `Look and listen. We will do one thing at a time.`;
    case "GRADE_7":
      return `Here is the big idea behind ${goal.toLowerCase()}, in two sentences.`;
    case "GRADE_8":
      return `Concept → tiny example → your turn to build. Hints first, answers later.`;
    case "GRADE_9":
      return `Concept, common pitfalls, and a worked example. Then practice with feedback.`;
    case "UNIVERSITY":
    case "PROFESSIONAL":
      return `Mental model, edge cases, and a hands-on exercise tied to the certification objective.`;
    case "SENIOR":
      return `Step by step. You can ask me to repeat or read aloud at any time.`;
  }
}

function tasksFor(stage: LearnerStage, goal: string, count: number): LessonTask[] {
  const base: LessonTask[] = [];
  switch (stage) {
    case "GRADE_6":
      base.push({
        prompt: "Can you count the apples? 🍎🍎🍎",
        choices: ["1", "2", "3", "4"],
        expected: "3",
      });
      break;
    case "GRADE_7":
      base.push(
        { prompt: `What is one fact you know about ${goal.toLowerCase()}?` },
        { prompt: "Pick the best answer in the mini quiz." },
        { prompt: "Tell me one new thing you learned." }
      );
      break;
    case "GRADE_8":
      base.push(
        { prompt: `Plan the steps to solve: ${goal}.` },
        {
          prompt: "Write a first attempt. Use a hint if stuck.",
          hint: "Start with the smallest working piece.",
        },
        { prompt: "Find one bug and fix it." },
        { prompt: "Explain in one sentence what you changed." }
      );
      break;
    case "GRADE_9":
      base.push(
        { prompt: `Define the key concept of ${goal} in your own words.` },
        { prompt: "Solve a typical exam-style question." },
        { prompt: "Identify the trap most students fall into." },
        { prompt: "Redo the question you got wrong, with feedback applied." },
        { prompt: "Summarise the rule you will remember tomorrow." }
      );
      break;
    case "UNIVERSITY":
    case "PROFESSIONAL":
      base.push(
        { prompt: `State the objective for ${goal} from the syllabus.` },
        { prompt: "Explain the underlying mental model." },
        { prompt: "Walk through a real-world scenario." },
        { prompt: "Answer two exam-grade questions." },
        { prompt: "Review one mistake and write a correction note." },
        { prompt: "Plan the next session topic." }
      );
      break;
    case "SENIOR":
      base.push(
        { prompt: `Try the first step for ${goal.toLowerCase()}. Take your time.` },
        { prompt: "Repeat it once on your own. I will watch and help." }
      );
      break;
  }
  return base.slice(0, count);
}

const LOOP_STEPS: LoopStepId[] = ["hook", "explain", "practice", "feedback", "reflect", "evolve"];

export function generateLesson(input: {
  stage: LearnerStage;
  goal: string;
  language?: string;
  teacherName?: string;
}): Lesson {
  const stage = input.stage;
  const defaults = STAGE_DEFAULTS[stage];
  const goal = input.goal?.trim() || "today's topic";
  const teacherName = input.teacherName ?? "Your teacher";

  const methodPlan = planForStage(stage);
  const exercises: Exercise[] = LOOP_STEPS.map((step) =>
    generateForMethod(methodPlan[step], step, { topic: goal, stage })
  );

  return {
    stage,
    goal,
    language: input.language ?? "en",
    attentionMinutes: defaults.attentionMinutes,
    teacherName,
    hook: hookFor(stage, goal, teacherName),
    explain: explainFor(stage, goal),
    tasks: tasksFor(stage, goal, defaults.tasks),
    reward: defaults.reward,
    methodPlan,
    exercises,
  };
}
